version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: luxe-nails-api
    container_name: luxe-nails-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - luxe-nails-network
    depends_on:
      - db
      - redis

  webserver:
    image: nginx:alpine
    container_name: luxe-nails-webserver
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - luxe-nails-network
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: luxe-nails-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: luxe_nails
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_PASSWORD: user_password
      MYSQL_USER: luxe_user
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    ports:
      - "3307:3306"
    networks:
      - luxe-nails-network

  redis:
    image: redis:alpine
    container_name: luxe-nails-redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    networks:
      - luxe-nails-network

volumes:
  dbdata:
    driver: local

networks:
  luxe-nails-network:
    driver: bridge
